### PR TITLE
pytests for #77 and #74

### PR DESCRIPTION
**Pull request by epogrebnyak**
I started a new folder `test_pytest` where I copied existing custonm tests and started a new unit test example `test_FinDate.py`.
This is the only test file where refactoring started and it is picked by `pytest`. 

In tests like `test_FinDate.py` we need to touch upon all public methods, but do not have to do any performance checks.

I left custom validation at `tests` where they were because there is probably some path dependecy embedded in their runner.
The remote custom runner is disabled, hoever file is preserved (yml renamed to txt).

Important change: requirements.txt is used in test setup and vesions are pinned to exact numbers. The reason for this is to avoid numba issue https://github.com/numba/numba/issues/6012 - we need exact 0.49 to run, 0.51 breaks tests silently even at tests collection.

We also perhaps need ipython and llvmlite in `setup.py` (not instroduced yet).

### CODE REVIEW

**Comment by domokane** [comment]
I didn't study this when you posted it. But as a todo list it looks fine.

**Comment by epogrebnyak** [comment]
This PR is superseded by #80

**Comment by domokane** [comment]
I am losing track of all these issues. Can we just keep the discussions in one issue.

**Comment by epogrebnyak** [comment]
We should make issues in one repo, but we cannot discuss everything in one
issue, that issue will never close. Usually one topic per issue.

вс, 7 мар. 2021 г., 14:06 domokane <notifications@github.com>:

**Comment by domokane** [comment]
It's confusing. Can we keep the discussions about the refactoring to this issue. Or we create three issues
- Refactoring and renaming to pep8 standards
- Unit Tests
- Documentation framework

**Pull request closed without merging**
