### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by sagayev**
Added NSS discount curve to curves init.py

### CODE REVIEW

**Review by domokane — CHANGES_REQUESTED** [review]
Shouldn't it be discount_curve_nss rather than dicount_curve_nss

**Comment by domokane** [comment]
I have made the change myself.

**Comment by domokane** [comment]
Thanks for spotting this.

**Comment by sagayev** [comment]
Thank you for spotting the typo. I will be careful next time.

**Comment by domokane** [comment]
No problem.

**Pull request closed without merging**
