### PR TITLE
pytests for #77 and #74 (to dev branch)

### PR DESCRIPTION
**Pull request by epogrebnyak**
I started a new folder `test_pytest` where I copied existing custonm tests and started a new unit test example `test_FinDate.py`.
This is the only test file where refactoring started and it is picked by `pytest`. 

In tests like `test_FinDate.py` we need to touch upon all public methods, but do not have to do any performance checks.

I left custom validation at `tests` where they were because there is probably some path dependecy embedded in their runner.
The remote custom runner is disabled, hoever file is preserved (yml renamed to txt).

Important change: requirements.txt is used in test setup and vesions are pinned to exact numbers. The reason for this is to avoid numba issue https://github.com/numba/numba/issues/6012 - we need exact 0.49 to run, 0.51 breaks tests silently even at tests collection.

We also perhaps need ipython and llvmlite in `setup.py` (not instroduced yet).

### CODE REVIEW

**Comment by epogrebnyak** [comment]
@domocane - try merge this to dev branch to make stable unit + "golden" tests

**Comment by domokane** [comment]
So I have to go through 113 files and reject the changes in all but 1 or 2 ?

**Comment by epogrebnyak** [comment]
> So I have to go through 113 files and reject the changes in all but 1 or 2 ?

No you have to merge entire branch, did you do that?

**Comment by domokane** [comment]
I followed the command line instructions. I merged it but rejected the incoming changes when they were in conflict with the latest version.

**Pull request closed without merging**
