### PR TITLE
move barrier option valuation functions to model

### PR DESCRIPTION
**Pull request by gpelleri**
hello @domokane 
I have moved the valuation equity barrier options valuations methods to a new model 
As I've updated "where" those functions are located, i have also generated update both test & golden test for barrier option accordingly. I have also generated a new golden test output for barrier option, but I am unsure it is really necessary
Please let me know if i'm missed something or If i missed the point of the issue

Best regards,
Gautier

### CODE REVIEW

**Comment by domokane** [comment]
Hi - this is a good start but I want the interface to the models folder to accept only low level types such as floats and integers. So we pass in the time to expiry in years and the option type as an integer and the risk free rate and dividend yields as a float.

**Comment by gpelleri** [comment]
Hello Sir @domokane 

I've amended my commit ans pushed correction, let me know if i missed something.

**Comment by domokane** [comment]
Hi - you are still passing a date into the model code. I only want to pass in floats and integers.

**Comment by domokane** [comment]
The Monte Carlo code takes a Date as an input. I only want floats.

**Pull request merged**
