### PR TITLE
plotted  the code for Multiple Assets One Time and Multiple Assets  and time

### PR DESCRIPTION
**Pull request by Akshat111111**
I have  plotted  the code for Multiple Assets One Time and Multiple Assets and Time which will enhance the understanding as well as the readability of the code, making it more interpretable

### CODE REVIEW

**Comment by Akshat111111** [comment]
Sir can you please merge this pull request

**Comment by Akshat111111** [comment]
The corresponding issue is Updated FINGBMPROCESS_generatePaths #203

**Comment by Akshat111111** [comment]
@domokane sir, I am writing to express my keen interest in working as a research intern under your guidance on the FinancePy project. With my strong foundation in computer science, mathematics, and machine learning, coupled with my passion for finance, I believe I can contribute meaningfully to your research while gaining invaluable experience in quantitative finance.

I am particularly drawn to FinancePy’s goal of providing a Python-based solution that bridges simplicity and high performance through Numba. The emphasis on product-based design and replicating real-world financial valuations aligns with my academic interests and technical expertise.

**Comment by domokane** [comment]
Hi Akshat
Sure. If you see stuff to do - look at issues - let me know before you begin.
Best
D


[Logo]<https://www.edhec.edu/fr>
Dominic O'KANE
Professeur
T : +33 4 93 18 99 66
393 promenade des Anglais BP 3116
06202 Nice Cedex 3
France
[Address-book]<https://data.sigilium.com/signatures/rchnyl0nd8mfiobdpgynr5xa0xyjwrc/link>
[Linkedin]<https://www.linkedin.com/school/edhec-business-school/>
[Twitter]<https://twitter.com/edhec_bschool?lang=fr>
[Facebook]<https://www.facebook.com/edhec/>
[Instagram]<https://www.instagram.com/edhec_bschool/?hl=en>

[https://data.sigilium.com/system/announcements/full_images/000/023/194/normal/FT-EURO-BS-2021---sigilium-uk.jpg]<https://data.sigilium.com/signatures/rchnyl0nd8mfiobdpgynr5xa0xyjwrc/redirect_link>


------ Original Message ------
From "Akshat Sharma" ***@***.******@***.***>>
To "domokane/FinancePy" ***@***.******@***.***>>
Cc "O'KANE Dominic" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 9/5/2024 5:29:45 PM
Subject Re: [domokane/FinancePy] plotted the code for Multiple Assets One Time and Multiple Assets and time (PR #206)


@domokane<https://urldefense.com/v3/__https://github.com/domokane__;!!AoFxdAc!1jf_bu8bd10JMyWfnmPgKN-KdJbs3iC1kK-K3a_mfcLhR6RTd3U-72D-qfa_AjVH_sDEJdxPg7iNw43IOdfH1mI7S5589g$> sir, I am writing to express my keen interest in working as a research intern under your guidance on the FinancePy project. With my strong foundation in computer science, mathematics, and machine learning, coupled with my passion for finance, I believe I can contribute meaningfully to your research while gaining invaluable experience in quantitative finance.

I am particularly drawn to FinancePy’s goal of providing a Python-based solution that bridges simplicity and high performance through Numba. The emphasis on product-based design and replicating real-world financial valuations aligns with my academic interests and technical expertise.

**Comment by domokane** [comment]
You deleted the old notebook and added a new one with a lot of install stuff at the top. This plot is ok but not enough to compensate for the deletion. I will add the plot in the new one I am reversing this PR.

**Pull request merged**
